# Generated by Django 6.1 on 2026-08-12 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Donation ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('donation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Donation date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], max_length=20, verbose_name='Payment method')),
                ('message', models.TextField(blank=True, verbose_name='Note / message')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='members.member', verbose_name='Member')),
            ],
            options={
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Payment ID')),
                ('payment_type', models.CharField(choices=[('MEMBERSHIP', 'Membership Fee'), ('RENEWAL', 'Renewal Fee'), ('EVENT', 'Event Fee')], max_length=20, verbose_name='Payment type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], max_length=20, verbose_name='Payment method')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member', verbose_name='Member')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
