# Generated by Django 6.1 on 2026-08-12 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Venue')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacity')),
                ('member_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Member price')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('audience', models.CharField(choices=[('ALL', 'All Members'), ('STUDENT', 'Student Members'), ('PROFESSIONAL', 'Professional Members'), ('CORPORATE', 'Corporate Members')], default='ALL', max_length=20, verbose_name='Audience')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Publish date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important')], default='NORMAL', max_length=10, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('audience', models.CharField(max_length=255, verbose_name='Recipients / audience')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='Recipients')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sent by')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Registration date')),
                ('attendance_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent')], default='REGISTERED', max_length=10, verbose_name='Attendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member', verbose_name='Member')),
            ],
            options={
                'ordering': ['registration_date'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
