# Generated by Django 6.1 on 2026-08-12 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Duration (months)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Member ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('join_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Join date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('last_renewed_date', models.DateField(blank=True, null=True, verbose_name='Last renewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.membershipplan', verbose_name='Membership plan')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
